//
//  PokemonMoveHelper.swift
//  IvStats
//
//  Created by LaiQiang on 2017-02-13.
//  Copyright © 2017 LaiQiang. All rights reserved.
//

import Foundation
import UIKit

struct PokemonMoveDetail {
    var pokemonMove: PokemonMove
    var moveType: PokemonType
    var dps: Float
    var damage: Float
    var time: Float
}

class PokemonMoveHelper
{
    
    class func getMoveDisplayName(forMove move: PokemonMove) -> String
    {
        var name = move.toString()
        name = name.replacingOccurrences(of: "_FAST", with: "")
        name = name.replacingOccurrences(of: "_", with: " ")
        name = name.lowercased()
        name = name.capitalized
        return name
    }
    
    class func getMoveTypeColor(forMove move: PokemonMove) -> UIColor
    {
        if let foundMove = pokemonMoveDetailDictionary[move]
        {
            return PokemonHelper.getTypeColor(withPokemonType: foundMove.moveType)
        }
        else
        {
            return PokemonHelper.getTypeColor(withPokemonType: PokemonType.pokemonTypeNone)
        }
    }
    
    class func getMoveType(forMove move: PokemonMove) -> PokemonType
    {
        if let foundMove = pokemonMoveDetailDictionary[move]
        {
            return foundMove.moveType
        }
        else
        {
            return PokemonType.pokemonTypeNone
        }
    }
    
    class func getMoveDPS(forMove move: PokemonMove) -> Float
    {
        if let foundMove = pokemonMoveDetailDictionary[move]
        {
            return foundMove.dps
        }
        else
        {
            return 0.0
        }
    }
    
    class func getMoveDamage(forMove move: PokemonMove) -> Float
    {
        if let foundMove = pokemonMoveDetailDictionary[move]
        {
            return foundMove.damage
        }
        else
        {
            return 0
        }
    }
    
    class func getBestAttackMoveSet(forPokemon pokemon: PokemonId) -> [PokemonMove]
    {
        if let foundMove = pokemonBestAttackMoveDictionary[pokemon]
        {
            return foundMove
        }
        else
        {
            return []
        }
    }
    
    class func getBestDefenseMoveSet(forPokemon pokemon: PokemonId) -> [PokemonMove]
    {
        if let foundMove = pokemonBestDefenseMoveDictionary[pokemon]
        {
            return foundMove
        }
        else
        {
            return []
        }
    }
    
    class func getBaseQuickMoveSet(forPokemon pokemon: PokemonId) -> [PokemonMove]
    {
        if let foundMove = pokemonBaseQuickMoveDictionary[pokemon]
        {
            return foundMove
        }
        else
        {
            return []
        }
    }
    
    class func getBaseMainMoveSet(forPokemon pokemon: PokemonId) -> [PokemonMove]
    {
        if let foundMove = pokemonBaseMainMoveDictionary[pokemon]
        {
            return foundMove
        }
        else
        {
            return []
        }
    }

    static var pokemonMoveDetailDictionary: [PokemonMove: PokemonMoveDetail] =
        [.wrap: PokemonMoveDetail.init(pokemonMove: .wrap, moveType: .pokemonTypeNormal, dps: 20.6897, damage: 60.0, time: 2.9),
         .hyperBeam: PokemonMoveDetail.init(pokemonMove: .hyperBeam, moveType: .pokemonTypeNormal, dps: 39.4737, damage: 150.0, time: 3.8),
         .darkPulse: PokemonMoveDetail.init(pokemonMove: .darkPulse, moveType: .pokemonTypeDark, dps: 26.6667, damage: 80.0, time: 3.0),
         .sludge: PokemonMoveDetail.init(pokemonMove: .sludge, moveType: .pokemonTypePoison, dps: 23.8095, damage: 50.0, time: 2.1),
         .viceGrip: PokemonMoveDetail.init(pokemonMove: .viceGrip, moveType: .pokemonTypeNormal, dps: 18.4211, damage: 35.0, time: 1.9),
         .flameWheel: PokemonMoveDetail.init(pokemonMove: .flameWheel, moveType: .pokemonTypeFire, dps: 22.2222, damage: 60.0, time: 2.7),
         .megahorn: PokemonMoveDetail.init(pokemonMove: .megahorn, moveType: .pokemonTypeBug, dps: 40.9091, damage: 90.0, time: 2.2),
         .flamethrower: PokemonMoveDetail.init(pokemonMove: .flamethrower, moveType: .pokemonTypeFire, dps: 31.8182, damage: 70.0, time: 2.2),
         .dig: PokemonMoveDetail.init(pokemonMove: .dig, moveType: .pokemonTypeGround, dps: 21.2766, damage: 100.0, time: 4.7),
         .crossChop: PokemonMoveDetail.init(pokemonMove: .crossChop, moveType: .pokemonTypeFighting, dps: 33.3333, damage: 50.0, time: 1.5),
         .psybeam: PokemonMoveDetail.init(pokemonMove: .psybeam, moveType: .pokemonTypePsychic, dps: 21.875, damage: 70.0, time: 3.2),
         .earthquake: PokemonMoveDetail.init(pokemonMove: .earthquake, moveType: .pokemonTypeGround, dps: 33.3333, damage: 120.0, time: 3.6),
         .stoneEdge: PokemonMoveDetail.init(pokemonMove: .stoneEdge, moveType: .pokemonTypeRock, dps: 43.4783, damage: 100.0, time: 2.3),
         .icePunch: PokemonMoveDetail.init(pokemonMove: .icePunch, moveType: .pokemonTypeIce, dps: 26.3158, damage: 50.0, time: 1.9),
         .heartStamp: PokemonMoveDetail.init(pokemonMove: .heartStamp, moveType: .pokemonTypePsychic, dps: 21.0526, damage: 40.0, time: 1.9),
         .discharge: PokemonMoveDetail.init(pokemonMove: .discharge, moveType: .pokemonTypeElectric, dps: 26.0, damage: 65.0, time: 2.5),
         .flashCannon: PokemonMoveDetail.init(pokemonMove: .flashCannon, moveType: .pokemonTypeSteel, dps: 37.037, damage: 100.0, time: 2.7),
         .drillPeck: PokemonMoveDetail.init(pokemonMove: .drillPeck, moveType: .pokemonTypeFlying, dps: 26.087, damage: 60.0, time: 2.3),
         .iceBeam: PokemonMoveDetail.init(pokemonMove: .iceBeam, moveType: .pokemonTypeIce, dps: 27.2727, damage: 90.0, time: 3.3),
         .blizzard: PokemonMoveDetail.init(pokemonMove: .blizzard, moveType: .pokemonTypeIce, dps: 41.9355, damage: 130.0, time: 3.1),
         .heatWave: PokemonMoveDetail.init(pokemonMove: .heatWave, moveType: .pokemonTypeFire, dps: 31.6667, damage: 95.0, time: 3.0),
         .aerialAce: PokemonMoveDetail.init(pokemonMove: .aerialAce, moveType: .pokemonTypeFlying, dps: 22.9167, damage: 55.0, time: 2.4),
         .drillRun: PokemonMoveDetail.init(pokemonMove: .drillRun, moveType: .pokemonTypeGround, dps: 28.5714, damage: 80.0, time: 2.8),
         .petalBlizzard: PokemonMoveDetail.init(pokemonMove: .petalBlizzard, moveType: .pokemonTypeGrass, dps: 42.3077, damage: 110.0, time: 2.6),
         .megaDrain: PokemonMoveDetail.init(pokemonMove: .megaDrain, moveType: .pokemonTypeGrass, dps: 9.61539, damage: 25.0, time: 2.6),
         .bugBuzz: PokemonMoveDetail.init(pokemonMove: .bugBuzz, moveType: .pokemonTypeBug, dps: 24.3243, damage: 90.0, time: 3.7),
         .poisonFang: PokemonMoveDetail.init(pokemonMove: .poisonFang, moveType: .pokemonTypePoison, dps: 20.5882, damage: 35.0, time: 1.7),
         .nightSlash: PokemonMoveDetail.init(pokemonMove: .nightSlash, moveType: .pokemonTypeDark, dps: 22.7273, damage: 50.0, time: 2.2),
         .bubbleBeam: PokemonMoveDetail.init(pokemonMove: .bubbleBeam, moveType: .pokemonTypeWater, dps: 23.6842, damage: 45.0, time: 1.9),
         .submission: PokemonMoveDetail.init(pokemonMove: .submission, moveType: .pokemonTypeFighting, dps: 27.2727, damage: 60.0, time: 2.2),
         .lowSweep: PokemonMoveDetail.init(pokemonMove: .lowSweep, moveType: .pokemonTypeFighting, dps: 21.0526, damage: 40.0, time: 1.9),
         .aquaJet: PokemonMoveDetail.init(pokemonMove: .aquaJet, moveType: .pokemonTypeWater, dps: 17.3077, damage: 45.0, time: 2.6),
         .aquaTail: PokemonMoveDetail.init(pokemonMove: .aquaTail, moveType: .pokemonTypeWater, dps: 26.3158, damage: 50.0, time: 1.9),
         .seedBomb: PokemonMoveDetail.init(pokemonMove: .seedBomb, moveType: .pokemonTypeGrass, dps: 26.1905, damage: 55.0, time: 2.1),
         .psyshock: PokemonMoveDetail.init(pokemonMove: .psyshock, moveType: .pokemonTypePsychic, dps: 24.0741, damage: 65.0, time: 2.7),
         .ancientPower: PokemonMoveDetail.init(pokemonMove: .ancientPower, moveType: .pokemonTypeRock, dps: 20.0, damage: 70.0, time: 3.5),
         .rockTomb: PokemonMoveDetail.init(pokemonMove: .rockTomb, moveType: .pokemonTypeRock, dps: 21.875, damage: 70.0, time: 3.2),
         .rockSlide: PokemonMoveDetail.init(pokemonMove: .rockSlide, moveType: .pokemonTypeRock, dps: 29.6296, damage: 80.0, time: 2.7),
         .powerGem: PokemonMoveDetail.init(pokemonMove: .powerGem, moveType: .pokemonTypeRock, dps: 27.5862, damage: 80.0, time: 2.9),
         .shadowSneak: PokemonMoveDetail.init(pokemonMove: .shadowSneak, moveType: .pokemonTypeGhost, dps: 17.2414, damage: 50.0, time: 2.9),
         .shadowPunch: PokemonMoveDetail.init(pokemonMove: .shadowPunch, moveType: .pokemonTypeGhost, dps: 23.5294, damage: 40.0, time: 1.7),
         .ominousWind: PokemonMoveDetail.init(pokemonMove: .ominousWind, moveType: .pokemonTypeGhost, dps: 21.7391, damage: 50.0, time: 2.3),
         .shadowBall: PokemonMoveDetail.init(pokemonMove: .shadowBall, moveType: .pokemonTypeGhost, dps: 33.3333, damage: 100.0, time: 3.0),
         .magnetBomb: PokemonMoveDetail.init(pokemonMove: .magnetBomb, moveType: .pokemonTypeSteel, dps: 25.0, damage: 70.0, time: 2.8),
         .ironHead: PokemonMoveDetail.init(pokemonMove: .ironHead, moveType: .pokemonTypeSteel, dps: 31.5789, damage: 60.0, time: 1.9),
         .parabolicCharge: PokemonMoveDetail.init(pokemonMove: .parabolicCharge, moveType: .pokemonTypeElectric, dps: 8.92857, damage: 25.0, time: 2.8),
         .thunderPunch: PokemonMoveDetail.init(pokemonMove: .thunderPunch, moveType: .pokemonTypeElectric, dps: 25.0, damage: 45.0, time: 1.8),
         .thunder: PokemonMoveDetail.init(pokemonMove: .thunder, moveType: .pokemonTypeElectric, dps: 41.6667, damage: 100.0, time: 2.4),
         .thunderbolt: PokemonMoveDetail.init(pokemonMove: .thunderbolt, moveType: .pokemonTypeElectric, dps: 32.0, damage: 80.0, time: 2.5),
         .twister: PokemonMoveDetail.init(pokemonMove: .twister, moveType: .pokemonTypeDragon, dps: 16.0714, damage: 45.0, time: 2.8),
         .dragonPulse: PokemonMoveDetail.init(pokemonMove: .dragonPulse, moveType: .pokemonTypeDragon, dps: 25.0, damage: 90.0, time: 3.6),
         .dragonClaw: PokemonMoveDetail.init(pokemonMove: .dragonClaw, moveType: .pokemonTypeDragon, dps: 29.4118, damage: 50.0, time: 1.7),
         .disarmingVoice: PokemonMoveDetail.init(pokemonMove: .disarmingVoice, moveType: .pokemonTypeFairy, dps: 17.9487, damage: 70.0, time: 3.9),
         .drainingKiss: PokemonMoveDetail.init(pokemonMove: .drainingKiss, moveType: .pokemonTypeFairy, dps: 23.0769, damage: 60.0, time: 2.6),
         .dazzlingGleam: PokemonMoveDetail.init(pokemonMove: .dazzlingGleam, moveType: .pokemonTypeFairy, dps: 28.5714, damage: 100.0, time: 3.5),
         .moonblast: PokemonMoveDetail.init(pokemonMove: .moonblast, moveType: .pokemonTypeFairy, dps: 33.3333, damage: 130.0, time: 3.9),
         .playRough: PokemonMoveDetail.init(pokemonMove: .playRough, moveType: .pokemonTypeFairy, dps: 31.0345, damage: 90.0, time: 2.9),
         .crossPoison: PokemonMoveDetail.init(pokemonMove: .crossPoison, moveType: .pokemonTypePoison, dps: 26.6667, damage: 40.0, time: 1.5),
         .sludgeBomb: PokemonMoveDetail.init(pokemonMove: .sludgeBomb, moveType: .pokemonTypePoison, dps: 34.7826, damage: 80.0, time: 2.3),
         .sludgeWave: PokemonMoveDetail.init(pokemonMove: .sludgeWave, moveType: .pokemonTypePoison, dps: 34.375, damage: 110.0, time: 3.2),
         .gunkShot: PokemonMoveDetail.init(pokemonMove: .gunkShot, moveType: .pokemonTypePoison, dps: 41.9355, damage: 130.0, time: 3.1),
         .boneClub: PokemonMoveDetail.init(pokemonMove: .boneClub, moveType: .pokemonTypeGround, dps: 25.0, damage: 40.0, time: 1.6),
         .bulldoze: PokemonMoveDetail.init(pokemonMove: .bulldoze, moveType: .pokemonTypeGround, dps: 22.8571, damage: 80.0, time: 3.5),
         .mudBomb: PokemonMoveDetail.init(pokemonMove: .mudBomb, moveType: .pokemonTypeGround, dps: 23.913, damage: 55.0, time: 2.3),
         .signalBeam: PokemonMoveDetail.init(pokemonMove: .signalBeam, moveType: .pokemonTypeBug, dps: 25.8621, damage: 75.0, time: 2.9),
         .xScissor: PokemonMoveDetail.init(pokemonMove: .xScissor, moveType: .pokemonTypeBug, dps: 28.125, damage: 45.0, time: 1.6),
         .flameCharge: PokemonMoveDetail.init(pokemonMove: .flameCharge, moveType: .pokemonTypeFire, dps: 18.4211, damage: 70.0, time: 3.8),
         .flameBurst: PokemonMoveDetail.init(pokemonMove: .flameBurst, moveType: .pokemonTypeFire, dps: 26.9231, damage: 70.0, time: 2.6),
         .fireBlast: PokemonMoveDetail.init(pokemonMove: .fireBlast, moveType: .pokemonTypeFire, dps: 33.3333, damage: 140.0, time: 4.2),
         .brine: PokemonMoveDetail.init(pokemonMove: .brine, moveType: .pokemonTypeWater, dps: 26.087, damage: 60.0, time: 2.3),
         .waterPulse: PokemonMoveDetail.init(pokemonMove: .waterPulse, moveType: .pokemonTypeWater, dps: 21.875, damage: 70.0, time: 3.2),
         .scald: PokemonMoveDetail.init(pokemonMove: .scald, moveType: .pokemonTypeWater, dps: 21.6216, damage: 80.0, time: 3.7),
         .hydroPump: PokemonMoveDetail.init(pokemonMove: .hydroPump, moveType: .pokemonTypeWater, dps: 39.3939, damage: 130.0, time: 3.3),
         .psychic: PokemonMoveDetail.init(pokemonMove: .psychic, moveType: .pokemonTypePsychic, dps: 35.7143, damage: 100.0, time: 2.8),
         .psystrike: PokemonMoveDetail.init(pokemonMove: .psystrike, moveType: .pokemonTypePsychic, dps: 22.7273, damage: 100.0, time: 4.4),
         .icyWind: PokemonMoveDetail.init(pokemonMove: .icyWind, moveType: .pokemonTypeIce, dps: 18.1818, damage: 60.0, time: 3.3),
         .gigaDrain: PokemonMoveDetail.init(pokemonMove: .gigaDrain, moveType: .pokemonTypeGrass, dps: 12.8205, damage: 50.0, time: 3.9),
         .firePunch: PokemonMoveDetail.init(pokemonMove: .firePunch, moveType: .pokemonTypeFire, dps: 25.0, damage: 55.0, time: 2.2),
         .solarBeam: PokemonMoveDetail.init(pokemonMove: .solarBeam, moveType: .pokemonTypeGrass, dps: 36.7347, damage: 180.0, time: 4.9),
         .leafBlade: PokemonMoveDetail.init(pokemonMove: .leafBlade, moveType: .pokemonTypeGrass, dps: 29.1667, damage: 70.0, time: 2.4),
         .powerWhip: PokemonMoveDetail.init(pokemonMove: .powerWhip, moveType: .pokemonTypeGrass, dps: 34.6154, damage: 90.0, time: 2.6),
         .airCutter: PokemonMoveDetail.init(pokemonMove: .airCutter, moveType: .pokemonTypeFlying, dps: 22.2222, damage: 60.0, time: 2.7),
         .hurricane: PokemonMoveDetail.init(pokemonMove: .hurricane, moveType: .pokemonTypeFlying, dps: 40.7407, damage: 110.0, time: 2.7),
         .brickBreak: PokemonMoveDetail.init(pokemonMove: .brickBreak, moveType: .pokemonTypeFighting, dps: 25.0, damage: 40.0, time: 1.6),
         .swift: PokemonMoveDetail.init(pokemonMove: .swift, moveType: .pokemonTypeNormal, dps: 21.4286, damage: 60.0, time: 2.8),
         .hornAttack: PokemonMoveDetail.init(pokemonMove: .hornAttack, moveType: .pokemonTypeNormal, dps: 21.6216, damage: 40.0, time: 1.85),
         .stomp: PokemonMoveDetail.init(pokemonMove: .stomp, moveType: .pokemonTypeNormal, dps: 32.3529, damage: 55.0, time: 1.7),
         .hyperFang: PokemonMoveDetail.init(pokemonMove: .hyperFang, moveType: .pokemonTypeNormal, dps: 32.0, damage: 80.0, time: 2.5),
         .bodySlam: PokemonMoveDetail.init(pokemonMove: .bodySlam, moveType: .pokemonTypeNormal, dps: 26.3158, damage: 50.0, time: 1.9),
         .rest: PokemonMoveDetail.init(pokemonMove: .rest, moveType: .pokemonTypeNormal, dps: 26.3158, damage: 50.0, time: 1.9),
         .struggle: PokemonMoveDetail.init(pokemonMove: .struggle, moveType: .pokemonTypeNormal, dps: 15.9091, damage: 35.0, time: 2.2),
         .scaldBlastoise: PokemonMoveDetail.init(pokemonMove: .scaldBlastoise, moveType: .pokemonTypeWater, dps: 10.6383, damage: 50.0, time: 4.7),
         .hydroPumpBlastoise: PokemonMoveDetail.init(pokemonMove: .hydroPumpBlastoise, moveType: .pokemonTypeWater, dps: 20.0, damage: 90.0, time: 4.5),
         .wrapGreen: PokemonMoveDetail.init(pokemonMove: .wrapGreen, moveType: .pokemonTypeNormal, dps: 8.62069, damage: 25.0, time: 2.9),
         .wrapPink: PokemonMoveDetail.init(pokemonMove: .wrapPink, moveType: .pokemonTypeNormal, dps: 8.62069, damage: 25.0, time: 2.9),
         .furyCutterFast: PokemonMoveDetail.init(pokemonMove: .furyCutterFast, moveType: .pokemonTypeBug, dps: 3.33333, damage: 3.0, time: 0.9),
         .bugBiteFast: PokemonMoveDetail.init(pokemonMove: .bugBiteFast, moveType: .pokemonTypeBug, dps: 5.26316, damage: 5.0, time: 0.95),
         .biteFast: PokemonMoveDetail.init(pokemonMove: .biteFast, moveType: .pokemonTypeDark, dps: 10.0, damage: 10.0, time: 1.0),
         .suckerPunchFast: PokemonMoveDetail.init(pokemonMove: .suckerPunchFast, moveType: .pokemonTypeDark, dps: 6.66667, damage: 8.0, time: 1.2),
         .dragonBreathFast: PokemonMoveDetail.init(pokemonMove: .dragonBreathFast, moveType: .pokemonTypeDragon, dps: 12.0, damage: 12.0, time: 1.0),
         .thunderShockFast: PokemonMoveDetail.init(pokemonMove: .thunderShockFast, moveType: .pokemonTypeElectric, dps: 5.45455, damage: 6.0, time: 1.1),
         .sparkFast: PokemonMoveDetail.init(pokemonMove: .sparkFast, moveType: .pokemonTypeElectric, dps: 6.66667, damage: 8.0, time: 1.2),
         .lowKickFast: PokemonMoveDetail.init(pokemonMove: .lowKickFast, moveType: .pokemonTypeFighting, dps: 5.45455, damage: 6.0, time: 1.1),
         .karateChopFast: PokemonMoveDetail.init(pokemonMove: .karateChopFast, moveType: .pokemonTypeFighting, dps: 6.15385, damage: 8.0, time: 1.3),
         .emberFast: PokemonMoveDetail.init(pokemonMove: .emberFast, moveType: .pokemonTypeFire, dps: 6.66667, damage: 10.0, time: 1.5),
         .wingAttackFast: PokemonMoveDetail.init(pokemonMove: .wingAttackFast, moveType: .pokemonTypeFlying, dps: 8.0, damage: 10.0, time: 1.25),
         .peckFast: PokemonMoveDetail.init(pokemonMove: .peckFast, moveType: .pokemonTypeFlying, dps: 6.66667, damage: 10.0, time: 1.5),
         .lickFast: PokemonMoveDetail.init(pokemonMove: .lickFast, moveType: .pokemonTypeGhost, dps: 5.0, damage: 5.0, time: 1.0),
         .shadowClawFast: PokemonMoveDetail.init(pokemonMove: .shadowClawFast, moveType: .pokemonTypeGhost, dps: 10.0, damage: 12.0, time: 1.2),
         .vineWhipFast: PokemonMoveDetail.init(pokemonMove: .vineWhipFast, moveType: .pokemonTypeGrass, dps: 7.27273, damage: 8.0, time: 1.1),
         .razorLeafFast: PokemonMoveDetail.init(pokemonMove: .razorLeafFast, moveType: .pokemonTypeGrass, dps: 10.0, damage: 15.0, time: 1.5),
         .mudShotFast: PokemonMoveDetail.init(pokemonMove: .mudShotFast, moveType: .pokemonTypeGround, dps: 8.57143, damage: 9.0, time: 1.05),
         .iceShardFast: PokemonMoveDetail.init(pokemonMove: .iceShardFast, moveType: .pokemonTypeIce, dps: 7.05882, damage: 12.0, time: 1.7),
         .frostBreathFast: PokemonMoveDetail.init(pokemonMove: .frostBreathFast, moveType: .pokemonTypeIce, dps: 7.14286, damage: 10.0, time: 1.4),
         .quickAttackFast: PokemonMoveDetail.init(pokemonMove: .quickAttackFast, moveType: .pokemonTypeNormal, dps: 8.0, damage: 10.0, time: 1.25),
         .scratchFast: PokemonMoveDetail.init(pokemonMove: .scratchFast, moveType: .pokemonTypeNormal, dps: 12.0, damage: 12.0, time: 1.0),
         .tackleFast: PokemonMoveDetail.init(pokemonMove: .tackleFast, moveType: .pokemonTypeNormal, dps: 10.0, damage: 10.0, time: 1.0),
         .poundFast: PokemonMoveDetail.init(pokemonMove: .poundFast, moveType: .pokemonTypeNormal, dps: 7.69231, damage: 8.0, time: 1.04),
         .cutFast: PokemonMoveDetail.init(pokemonMove: .cutFast, moveType: .pokemonTypeNormal, dps: 10.0, damage: 10.0, time: 1.0),
         .poisonJabFast: PokemonMoveDetail.init(pokemonMove: .poisonJabFast, moveType: .pokemonTypePoison, dps: 9.23077, damage: 12.0, time: 1.3),
         .acidFast: PokemonMoveDetail.init(pokemonMove: .acidFast, moveType: .pokemonTypePoison, dps: 7.69231, damage: 10.0, time: 1.3),
         .psychoCutFast: PokemonMoveDetail.init(pokemonMove: .psychoCutFast, moveType: .pokemonTypePsychic, dps: 7.47663, damage: 8.0, time: 1.07),
         .rockThrowFast: PokemonMoveDetail.init(pokemonMove: .rockThrowFast, moveType: .pokemonTypeRock, dps: 8.57143, damage: 12.0, time: 1.4),
         .metalClawFast: PokemonMoveDetail.init(pokemonMove: .metalClawFast, moveType: .pokemonTypeSteel, dps: 7.07965, damage: 8.0, time: 1.13),
         .bulletPunchFast: PokemonMoveDetail.init(pokemonMove: .bulletPunchFast, moveType: .pokemonTypeSteel, dps: 8.57143, damage: 12.0, time: 1.4),
         .waterGunFast: PokemonMoveDetail.init(pokemonMove: .waterGunFast, moveType: .pokemonTypeWater, dps: 10.0, damage: 10.0, time: 1.0),
         .splashFast: PokemonMoveDetail.init(pokemonMove: .splashFast, moveType: .pokemonTypeWater, dps: 0.0, damage: 0.0, time: 1.73),
         .waterGunFastBlastoise: PokemonMoveDetail.init(pokemonMove: .waterGunFastBlastoise, moveType: .pokemonTypeWater, dps: 10.0, damage: 10.0, time: 1.0),
         .mudSlapFast: PokemonMoveDetail.init(pokemonMove: .mudSlapFast, moveType: .pokemonTypeGround, dps: 8.10811, damage: 15.0, time: 1.85),
         .zenHeadbuttFast: PokemonMoveDetail.init(pokemonMove: .zenHeadbuttFast, moveType: .pokemonTypePsychic, dps: 7.74194, damage: 12.0, time: 1.55),
         .confusionFast: PokemonMoveDetail.init(pokemonMove: .confusionFast, moveType: .pokemonTypePsychic, dps: 9.52381, damage: 20.0, time: 2.1),
         .poisonStingFast: PokemonMoveDetail.init(pokemonMove: .poisonStingFast, moveType: .pokemonTypePoison, dps: 5.5814, damage: 6.0, time: 1.075),
         .bubbleFast: PokemonMoveDetail.init(pokemonMove: .bubbleFast, moveType: .pokemonTypeWater, dps: 8.82353, damage: 15.0, time: 1.7),
         .feintAttackFast: PokemonMoveDetail.init(pokemonMove: .feintAttackFast, moveType: .pokemonTypeDark, dps: 8.57143, damage: 12.0, time: 1.4),
         .steelWingFast: PokemonMoveDetail.init(pokemonMove: .steelWingFast, moveType: .pokemonTypeSteel, dps: 9.23077, damage: 12.0, time: 1.3),
         .fireFangFast: PokemonMoveDetail.init(pokemonMove: .fireFangFast, moveType: .pokemonTypeFire, dps: 8.95522, damage: 12.0, time: 1.34),
         .rockSmashFast: PokemonMoveDetail.init(pokemonMove: .rockSmashFast, moveType: .pokemonTypeFighting, dps: 8.82353, damage: 15.0, time: 1.7),
         .transformFast: PokemonMoveDetail.init(pokemonMove: .transformFast, moveType: .pokemonTypeNormal, dps: 0.0, damage: 0.0, time: 2.23),
         .counterFast: PokemonMoveDetail.init(pokemonMove: .counterFast, moveType: .pokemonTypeFighting, dps: 11.1111, damage: 10.0, time: 0.9),
         .powderSnowFast: PokemonMoveDetail.init(pokemonMove: .powderSnowFast, moveType: .pokemonTypeIce, dps: 6.0, damage: 6.0, time: 1.0),
         .closeCombat: PokemonMoveDetail.init(pokemonMove: .closeCombat, moveType: .pokemonTypeFighting, dps: 43.4783, damage: 100.0, time: 2.3),
         .dynamicPunch: PokemonMoveDetail.init(pokemonMove: .dynamicPunch, moveType: .pokemonTypeFighting, dps: 33.3333, damage: 90.0, time: 2.7),
         .focusBlast: PokemonMoveDetail.init(pokemonMove: .focusBlast, moveType: .pokemonTypeFighting, dps: 40.0, damage: 140.0, time: 3.5),
         .auroraBeam: PokemonMoveDetail.init(pokemonMove: .auroraBeam, moveType: .pokemonTypeIce, dps: 22.5352, damage: 80.0, time: 3.55),
         .chargeBeamFast: PokemonMoveDetail.init(pokemonMove: .chargeBeamFast, moveType: .pokemonTypeElectric, dps: 5.16129, damage: 8.0, time: 1.55),
         .voltSwitchFast: PokemonMoveDetail.init(pokemonMove: .voltSwitchFast, moveType: .pokemonTypeElectric, dps: 5.21739, damage: 12.0, time: 2.3),
         .wildCharge: PokemonMoveDetail.init(pokemonMove: .wildCharge, moveType: .pokemonTypeElectric, dps: 34.6154, damage: 90.0, time: 2.6),
         .zapCannon: PokemonMoveDetail.init(pokemonMove: .zapCannon, moveType: .pokemonTypeElectric, dps: 37.8378, damage: 140.0, time: 3.7),
         .dragonTailFast: PokemonMoveDetail.init(pokemonMove: .dragonTailFast, moveType: .pokemonTypeDragon, dps: 9.67742, damage: 15.0, time: 1.55),
         .avalanche: PokemonMoveDetail.init(pokemonMove: .avalanche, moveType: .pokemonTypeIce, dps: 33.3333, damage: 90.0, time: 2.7),
         .airSlashFast: PokemonMoveDetail.init(pokemonMove: .airSlashFast, moveType: .pokemonTypeFlying, dps: 10.0, damage: 12.0, time: 1.2),
         .braveBird: PokemonMoveDetail.init(pokemonMove: .braveBird, moveType: .pokemonTypeFlying, dps: 45.0, damage: 90.0, time: 2.0),
         .skyAttack: PokemonMoveDetail.init(pokemonMove: .skyAttack, moveType: .pokemonTypeFlying, dps: 35.0, damage: 70.0, time: 2.0),
         .sandTomb: PokemonMoveDetail.init(pokemonMove: .sandTomb, moveType: .pokemonTypeGround, dps: 20.0, damage: 80.0, time: 4.0),
         .rockBlast: PokemonMoveDetail.init(pokemonMove: .rockBlast, moveType: .pokemonTypeRock, dps: 23.8095, damage: 50.0, time: 2.1),
         .infestationFast: PokemonMoveDetail.init(pokemonMove: .infestationFast, moveType: .pokemonTypeBug, dps: 6.45161, damage: 10.0, time: 1.55),
         .struggleBugFast: PokemonMoveDetail.init(pokemonMove: .struggleBugFast, moveType: .pokemonTypeBug, dps: 4.0, damage: 6.0, time: 1.5),
         .silverWind: PokemonMoveDetail.init(pokemonMove: .silverWind, moveType: .pokemonTypeBug, dps: 18.9189, damage: 70.0, time: 3.7),
         .astonishFast: PokemonMoveDetail.init(pokemonMove: .astonishFast, moveType: .pokemonTypeGhost, dps: 7.61905, damage: 8.0, time: 1.05),
         .hexFast: PokemonMoveDetail.init(pokemonMove: .hexFast, moveType: .pokemonTypeGhost, dps: 8.33333, damage: 10.0, time: 1.2),
         .nightShade: PokemonMoveDetail.init(pokemonMove: .nightShade, moveType: .pokemonTypeGhost, dps: 23.0769, damage: 60.0, time: 2.6),
         .ironTailFast: PokemonMoveDetail.init(pokemonMove: .ironTailFast, moveType: .pokemonTypeSteel, dps: 9.67742, damage: 15.0, time: 1.55),
         .gyroBall: PokemonMoveDetail.init(pokemonMove: .gyroBall, moveType: .pokemonTypeSteel, dps: 24.2424, damage: 80.0, time: 3.3),
         .heavySlam: PokemonMoveDetail.init(pokemonMove: .heavySlam, moveType: .pokemonTypeSteel, dps: 33.3333, damage: 70.0, time: 2.1),
         .fireSpinFast: PokemonMoveDetail.init(pokemonMove: .fireSpinFast, moveType: .pokemonTypeFire, dps: 9.67742, damage: 15.0, time: 1.55),
         .overheat: PokemonMoveDetail.init(pokemonMove: .overheat, moveType: .pokemonTypeFire, dps: 40.0, damage: 160.0, time: 4.0),
         .bulletSeedFast: PokemonMoveDetail.init(pokemonMove: .bulletSeedFast, moveType: .pokemonTypeGrass, dps: 5.16129, damage: 8.0, time: 1.55),
         .grassKnot: PokemonMoveDetail.init(pokemonMove: .grassKnot, moveType: .pokemonTypeGrass, dps: 34.6154, damage: 90.0, time: 2.6),
         .energyBall: PokemonMoveDetail.init(pokemonMove: .energyBall, moveType: .pokemonTypeGrass, dps: 23.0769, damage: 90.0, time: 3.9),
         .extrasensoryFast: PokemonMoveDetail.init(pokemonMove: .extrasensoryFast, moveType: .pokemonTypePsychic, dps: 7.74194, damage: 12.0, time: 1.55),
         .futuresight: PokemonMoveDetail.init(pokemonMove: .futuresight, moveType: .pokemonTypePsychic, dps: 44.4444, damage: 120.0, time: 2.7),
         .mirrorCoat: PokemonMoveDetail.init(pokemonMove: .mirrorCoat, moveType: .pokemonTypePsychic, dps: 23.0769, damage: 60.0, time: 2.6),
         .outrage: PokemonMoveDetail.init(pokemonMove: .outrage, moveType: .pokemonTypeDragon, dps: 28.2051, damage: 110.0, time: 3.9),
         .snarlFast: PokemonMoveDetail.init(pokemonMove: .snarlFast, moveType: .pokemonTypeDark, dps: 7.74194, damage: 12.0, time: 1.55),
         .crunch: PokemonMoveDetail.init(pokemonMove: .crunch, moveType: .pokemonTypeDark, dps: 21.875, damage: 70.0, time: 3.2),
         .foulPlay: PokemonMoveDetail.init(pokemonMove: .foulPlay, moveType: .pokemonTypeDark, dps: 35.0, damage: 70.0, time: 2.0),
         .hiddenPowerFast: PokemonMoveDetail.init(pokemonMove: .hiddenPowerFast, moveType: .pokemonTypeNormal, dps: 6.66667, damage: 10.0, time: 1.5),
         ]
    
    static let pokemonBestAttackMoveDictionary: [PokemonId: [PokemonMove]] =
        [
            .bulbasaur: [.vineWhipFast,.powerWhip],
            .ivysaur: [.razorLeafFast,.solarBeam],
            .venusaur: [.razorLeafFast,.solarBeam],
            .charmander: [.scratchFast,.flamethrower],
            .charmeleon: [.fireFangFast,.flamethrower],
            .charizard: [.airSlashFast,.overheat],
            .squirtle: [.bubbleFast,.aquaTail],
            .wartortle: [.waterGunFast,.hydroPump],
            .blastoise: [.waterGunFast,.hydroPump],
            .caterpie: [.tackleFast,.struggle],
            .metapod: [.tackleFast,.struggle],
            .butterfree: [.confusionFast,.bugBuzz],
            .weedle: [.poisonStingFast,.struggle],
            .kakuna: [.poisonStingFast,.struggle],
            .beedrill: [.poisonJabFast,.sludgeBomb],
            .pidgey: [.tackleFast,.aerialAce],
            .pidgeotto: [.wingAttackFast,.aerialAce],
            .pidgeot: [.airSlashFast,.hurricane],
            .rattata: [.tackleFast,.hyperFang],
            .raticate: [.quickAttackFast,.hyperBeam],
            .spearow: [.quickAttackFast,.drillPeck],
            .fearow: [.steelWingFast,.skyAttack],
            .ekans: [.acidFast,.sludgeBomb],
            .arbok: [.acidFast,.gunkShot],
            .pikachu: [.thunderShockFast,.wildCharge],
            .raichu: [.voltSwitchFast,.wildCharge],
            .sandshrew: [.scratchFast,.dig],
            .sandslash: [.mudShotFast,.earthquake],
            .nidoranFemale: [.biteFast,.sludgeBomb],
            .nidorina: [.biteFast,.sludgeBomb],
            .nidoqueen: [.poisonJabFast,.earthquake],
            .nidoranMale: [.poisonStingFast,.sludgeBomb],
            .nidorino: [.poisonJabFast,.sludgeBomb],
            .nidoking: [.poisonJabFast,.earthquake],
            .clefairy: [.zenHeadbuttFast,.moonblast],
            .clefable: [.chargeBeamFast,.dazzlingGleam],
            .vulpix: [.emberFast,.flamethrower],
            .ninetales: [.fireSpinFast,.overheat],
            .jigglypuff: [.feintAttackFast,.dazzlingGleam],
            .wigglytuff: [.poundFast,.hyperBeam],
            .zubat: [.biteFast,.airCutter],
            .golbat: [.wingAttackFast,.shadowBall],
            .oddish: [.razorLeafFast,.sludgeBomb],
            .gloom: [.razorLeafFast,.sludgeBomb],
            .vileplume: [.razorLeafFast,.solarBeam],
            .paras: [.scratchFast,.seedBomb],
            .parasect: [.struggleBugFast,.solarBeam],
            .venonat: [.confusionFast,.signalBeam],
            .venomoth: [.infestationFast,.bugBuzz],
            .diglett: [.scratchFast,.dig],
            .dugtrio: [.mudSlapFast,.mudBomb],
            .meowth: [.scratchFast,.foulPlay],
            .persian: [.scratchFast,.playRough],
            .psyduck: [.waterGunFast,.aquaTail],
            .golduck: [.waterGunFast,.hydroPump],
            .mankey: [.scratchFast,.crossChop],
            .primeape: [.counterFast,.closeCombat],
            .growlithe: [.biteFast,.flamethrower],
            .arcanine: [.fireFangFast,.fireBlast],
            .poliwag: [.bubbleFast,.bubbleBeam],
            .poliwhirl: [.bubbleFast,.waterPulse],
            .poliwrath: [.bubbleFast,.dynamicPunch],
            .abra: [.zenHeadbuttFast,.psyshock],
            .kadabra: [.confusionFast,.shadowBall],
            .alakazam: [.confusionFast,.futuresight],
            .machop: [.rockSmashFast, .crossChop],
            .machoke: [.karateChopFast,.dynamicPunch],
            .machamp: [.rockSmashFast,.crossChop],
            .bellsprout: [.acidFast,.powerWhip],
            .weepinbell: [.acidFast,.powerWhip],
            .victreebel: [.razorLeafFast,.solarBeam],
            .tentacool: [.bubbleFast,.waterPulse],
            .tentacruel: [.poisonJabFast,.hydroPump],
            .geodude: [.rockThrowFast,.rockSlide],
            .graveler: [.rockThrowFast,.stoneEdge],
            .golem: [.rockThrowFast,.stoneEdge],
            .ponyta: [.tackleFast,.flameCharge],
            .rapidash: [.fireSpinFast,.fireBlast],
            .slowpoke: [.waterGunFast,.psyshock],
            .slowbro: [.waterGunFast,.psychic],
            .magnemite: [.sparkFast,.magnetBomb],
            .magneton: [.chargeBeamFast,.magnetBomb],
            .farfetchd: [.airSlashFast,.leafBlade],
            .doduo: [.quickAttackFast,.drillPeck],
            .dodrio: [.feintAttackFast,.drillPeck],
            .seel: [.iceShardFast,.aquaTail],
            .dewgong: [.frostBreathFast,.blizzard],
            .grimer: [.poisonJabFast,.sludgeBomb],
            .muk: [.poisonJabFast,.gunkShot],
            .shellder: [.tackleFast,.bubbleBeam],
            .cloyster: [.iceShardFast,.avalanche],
            .gastly: [.astonishFast,.sludgeBomb],
            .haunter: [.astonishFast,.sludgeBomb],
            .gengar: [.hexFast,.shadowBall],
            .onix: [.rockThrowFast,.stoneEdge],
            .drowzee: [.confusionFast,.psyshock],
            .hypno: [.confusionFast,.futuresight],
            .krabby: [.bubbleFast,.waterPulse],
            .kingler: [.bubbleFast,.waterPulse],
            .voltorb: [.tackleFast,.discharge],
            .electrode: [.voltSwitchFast,.thunderbolt],
            .exeggcute: [.confusionFast,.seedBomb],
            .exeggutor: [.extrasensoryFast,.solarBeam],
            .cubone: [.mudSlapFast,.dig],
            .marowak: [.mudSlapFast,.dig],
            .hitmonlee: [.rockSmashFast,.closeCombat],
            .hitmonchan: [.counterFast,.closeCombat],
            .lickitung: [.zenHeadbuttFast,.hyperBeam],
            .koffing: [.infestationFast,.sludgeBomb],
            .weezing: [.infestationFast,.sludgeBomb],
            .rhyhorn: [.mudSlapFast,.bulldoze],
            .rhydon: [.mudSlapFast,.stoneEdge],
            .chansey: [.poundFast,.hyperBeam],
            .tangela: [.vineWhipFast,.grassKnot],
            .kangaskhan: [.mudSlapFast,.outrage],
            .horsea: [.waterGunFast,.bubbleBeam],
            .seadra: [.waterGunFast,.hydroPump],
            .goldeen: [.mudShotFast,.aquaTail],
            .seaking: [.poisonJabFast,.iceBeam],
            .staryu: [.waterGunFast,.bubbleBeam],
            .starmie: [.waterGunFast,.hydroPump],
            .mrMime: [.confusionFast,.shadowBall],
            .scyther: [.airSlashFast,.xScissor],
            .jynx: [.confusionFast,.avalanche],
            .electabuzz: [.thunderShockFast,.thunderbolt],
            .magmar: [.emberFast,.fireBlast],
            .pinsir: [.rockSmashFast,.xScissor],
            .tauros: [.tackleFast,.earthquake],
            .magikarp: [.splashFast,.struggle],
            .gyarados: [.biteFast,.outrage],
            .lapras: [.waterGunFast,.iceBeam],
            .ditto: [.transformFast,.struggle],
            .eevee: [.tackleFast,.swift],
            .vaporeon: [.waterGunFast,.hydroPump],
            .jolteon: [.thunderShockFast,.thunderbolt],
            .flareon: [.fireSpinFast,.overheat],
            .porygon: [.hiddenPowerFast, .hyperBeam],
            .omanyte: [.waterGunFast,.ancientPower],
            .omastar: [.waterGunFast,.hydroPump],
            .kabuto: [.scratchFast,.ancientPower],
            .kabutops: [.mudShotFast,.ancientPower],
            .aerodactyl: [.biteFast,.ancientPower],
            .snorlax: [.zenHeadbuttFast,.hyperBeam],
            .articuno: [.frostBreathFast,.iceBeam],
            .zapdos: [.chargeBeamFast,.thunderbolt],
            .moltres: [.chargeBeamFast,.thunderbolt],
            .dratini: [.dragonBreathFast,.aquaTail],
            .dragonair: [.dragonBreathFast,.dragonPulse],
            .dragonite: [.steelWingFast,.outrage],
            .mewtwo: [.confusionFast,.shadowBall],
            .mew: [.poundFast,.hyperBeam],
            .chikorita: [.vineWhipFast,.grassKnot],
            .bayleef: [.razorLeafFast,.grassKnot],
            .meganium: [.razorLeafFast,.solarBeam],
            .cyndaquil: [.tackleFast,.flamethrower],
            .quilava: [.tackleFast,.flamethrower],
            .typhlosion: [.emberFast,.overheat],
            .totodile: [.scratchFast,.waterPulse],
            .croconaw: [.scratchFast,.waterPulse],
            .feraligatr: [.waterGunFast,.hydroPump],
            .sentret: [.scratchFast,.grassKnot],
            .furret: [.quickAttackFast,.hyperBeam],
            .hoothoot: [.feintAttackFast,.skyAttack],
            .noctowl: [.wingAttackFast,.skyAttack],
            .ledyba: [.tackleFast,.silverWind],
            .ledian: [.bugBiteFast,.bugBuzz],
            .spinarak: [.poisonStingFast,.signalBeam],
            .ariados: [.infestationFast,.crossPoison],
            .crobat: [.airSlashFast,.sludgeBomb],
            .chinchou: [.bubbleFast,.thunderbolt],
            .lanturn: [.waterGunFast,.thunderbolt],
            .pichu: [.thunderShockFast,.thunderbolt],
            .cleffa: [.zenHeadbuttFast,.grassKnot],
            .igglybuff: [.poundFast,.shadowBall],
            .togepi: [.hiddenPowerFast,.dazzlingGleam],
            .togetic: [.hiddenPowerFast,.dazzlingGleam],
            .natu: [.peckFast,.drillPeck],
            .xatu: [.airSlashFast,.futuresight],
            .mareep: [.thunderShockFast,.thunderbolt],
            .flaaffy: [.chargeBeamFast,.thunderbolt],
            .ampharos: [.chargeBeamFast,.zapCannon],
            .bellossom: [.razorLeafFast,.leafBlade],
            .marill: [.bubbleFast,.aquaTail],
            .azumarill: [.bubbleFast,.playRough],
            .sudowoodo: [.counterFast,.rockSlide],
            .politoed: [.bubbleFast,.hydroPump],
            .hoppip: [.bulletSeedFast,.grassKnot],
            .skiploom: [.bulletSeedFast,.grassKnot],
            .jumpluff: [.infestationFast,.solarBeam],
            .aipom: [.scratchFast,.swift],
            .sunkern: [.razorLeafFast,.grassKnot],
            .sunflora: [.razorLeafFast,.solarBeam],
            .yanma: [.wingAttackFast,.aerialAce],
            .wooper: [.waterGunFast,.dig],
            .quagsire: [.waterGunFast,.sludgeBomb],
            .espeon: [.confusionFast,.futuresight],
            .umbreon: [.feintAttackFast,.foulPlay],
            .murkrow: [.feintAttackFast,.foulPlay],
            .slowking: [.waterGunFast,.psychic],
            .misdreavus: [.hexFast,.ominousWind],
            .unown: [.hiddenPowerFast,.struggle],
            .wobbuffet: [.counterFast,.mirrorCoat],
            .girafarig: [.tackleFast,.psychic],
            .pineco: [.tackleFast,.gyroBall],
            .forretress: [.struggleBugFast,.heavySlam],
            .dunsparce: [.astonishFast,.rockSlide],
            .gligar: [.wingAttackFast,.dig],
            .steelix: [.ironTailFast,.heavySlam],
            .snubbull: [.biteFast,.dazzlingGleam],
            .granbull: [.snarlFast,.playRough],
            .qwilfish: [.waterGunFast,.aquaTail],
            .scizor: [.bulletPunchFast,.ironHead],
            .shuckle: [.rockThrowFast,.stoneEdge],
            .heracross: [.counterFast,.closeCombat],
            .sneasel: [.feintAttackFast,.avalanche],
            .teddiursa: [.scratchFast,.playRough],
            .ursaring: [.counterFast,.hyperBeam],
            .slugma: [.rockThrowFast,.flameBurst],
            .magcargo: [.rockThrowFast,.overheat],
            .swinub: [.powderSnowFast,.rockSlide],
            .piloswine: [.powderSnowFast,.avalanche],
            .corsola: [.bubbleFast,.powerGem],
            .remoraid: [.waterGunFast,.waterPulse],
            .octillery: [.waterGunFast,.gunkShot],
            .delibird: [.iceShardFast,.icePunch],
            .mantine: [.bubbleFast,.aerialAce],
            .skarmory: [.airSlashFast,.skyAttack],
            .houndour: [.feintAttackFast,.flamethrower],
            .houndoom: [.fireFangFast,.foulPlay],
            .kingdra: [.dragonBreathFast,.outrage],
            .phanpy: [.tackleFast,.bulldoze],
            .donphan: [.counterFast,.earthquake],
            .porygon2: [.hiddenPowerFast,.hyperBeam],
            .stantler: [.tackleFast,.wildCharge],
            .smeargle: [.tackleFast,.struggle],
            .tyrogue: [.rockSmashFast,.rockSlide],
            .hitmontop: [.counterFast,.closeCombat],
            .smoochum: [.powderSnowFast,.iceBeam],
            .elekid: [.thunderShockFast,.discharge],
            .magby: [.emberFast,.firePunch],
            .miltank: [.tackleFast,.bodySlam],
            .blissey: [.poundFast,.hyperBeam],
            .raikou: [.voltSwitchFast,.wildCharge],
            .entei: [.fireSpinFast,.overheat],
            .suicune: [.extrasensoryFast,.hydroPump],
            .larvitar: [.biteFast,.ancientPower],
            .pupitar: [.biteFast,.dig],
            .tyranitar: [.biteFast,.stoneEdge],
            .lugia: [.extrasensoryFast,.skyAttack],
            .hoOh: [.extrasensoryFast,.fireBlast],
            .celebi: [.confusionFast,.hyperBeam]
    ]
    
    static let pokemonBestDefenseMoveDictionary: [PokemonId: [PokemonMove]] =
        [
            .bulbasaur: [.tackleFast,.powerWhip],
            .ivysaur: [.razorLeafFast,.solarBeam],
            .venusaur: [.razorLeafFast,.solarBeam],
            .charmander: [.emberFast,.flameCharge],
            .charmeleon: [.fireFangFast,.flamethrower],
            .charizard: [.fireSpinFast,.overheat],
            .squirtle: [.bubbleFast,.waterPulse],
            .wartortle: [.waterGunFast,.iceBeam],
            .blastoise: [.waterGunFast,.iceBeam],
            .caterpie: [.tackleFast,.struggle],
            .metapod: [.tackleFast,.struggle],
            .butterfree: [.confusionFast,.bugBuzz],
            .weedle: [.poisonStingFast,.struggle],
            .kakuna: [.poisonStingFast,.struggle],
            .beedrill: [.infestationFast,.sludgeBomb],
            .pidgey: [.quickAttackFast,.aerialAce],
            .pidgeotto: [.wingAttackFast,.aerialAce],
            .pidgeot: [.airSlashFast,.aerialAce],
            .rattata: [.quickAttackFast,.hyperFang],
            .raticate: [.quickAttackFast,.hyperFang],
            .spearow: [.peckFast,.drillPeck],
            .fearow: [.peckFast,.aerialAce],
            .ekans: [.acidFast,.sludgeBomb],
            .arbok: [.acidFast,.gunkShot],
            .pikachu: [.quickAttackFast,.wildCharge],
            .raichu: [.voltSwitchFast,.wildCharge],
            .sandshrew: [.scratchFast,.dig],
            .sandslash: [.mudShotFast,.earthquake],
            .nidoranFemale: [.poisonStingFast,.sludgeBomb],
            .nidorina: [.poisonStingFast,.sludgeBomb],
            .nidoqueen: [.poisonJabFast,.earthquake],
            .nidoranMale: [.peckFast,.sludgeBomb],
            .nidorino: [.poisonJabFast,.sludgeBomb],
            .nidoking: [.poisonJabFast,.earthquake],
            .clefairy: [.zenHeadbuttFast,.moonblast],
            .clefable: [.chargeBeamFast,.dazzlingGleam],
            .vulpix: [.emberFast,.flameCharge],
            .ninetales: [.fireSpinFast,.overheat],
            .jigglypuff: [.feintAttackFast,.dazzlingGleam],
            .wigglytuff: [.feintAttackFast,.dazzlingGleam],
            .zubat: [.quickAttackFast,.airCutter],
            .golbat: [.wingAttackFast,.shadowBall],
            .oddish: [.razorLeafFast,.sludgeBomb],
            .gloom: [.razorLeafFast,.sludgeBomb],
            .vileplume: [.razorLeafFast,.solarBeam],
            .paras: [.scratchFast,.seedBomb],
            .parasect: [.struggleBugFast,.solarBeam],
            .venonat: [.confusionFast,.signalBeam],
            .venomoth: [.confusionFast,.bugBuzz],
            .diglett: [.mudSlapFast,.dig],
            .dugtrio: [.mudSlapFast,.mudBomb],
            .meowth: [.scratchFast,.foulPlay],
            .persian: [.scratchFast,.playRough],
            .psyduck: [.waterGunFast,.aquaTail],
            .golduck: [.confusionFast,.hydroPump],
            .mankey: [.scratchFast,.crossChop],
            .primeape: [.counterFast,.closeCombat],
            .growlithe: [.emberFast,.flamethrower],
            .arcanine: [.fireFangFast,.wildCharge],
            .poliwag: [.bubbleFast,.bubbleBeam],
            .poliwhirl: [.bubbleFast,.waterPulse],
            .poliwrath: [.bubbleFast,.dynamicPunch],
            .abra: [.zenHeadbuttFast,.psyshock],
            .kadabra: [.confusionFast,.shadowBall],
            .alakazam: [.confusionFast,.shadowBall],
            .machop: [.rockSmashFast, .brickBreak],
            .machoke: [.karateChopFast,.dynamicPunch],
            .machamp: [.rockSmashFast,.brickBreak],
            .bellsprout: [.acidFast,.powerWhip],
            .weepinbell: [.bulletSeedFast,.powerWhip],
            .victreebel: [.razorLeafFast,.solarBeam],
            .tentacool: [.bubbleFast,.waterPulse],
            .tentacruel: [.poisonJabFast,.hydroPump],
            .geodude: [.rockThrowFast,.dig],
            .graveler: [.mudSlapFast,.dig],
            .golem: [.mudSlapFast,.rockBlast],
            .ponyta: [.emberFast,.flameCharge],
            .rapidash: [.fireSpinFast,.fireBlast],
            .slowpoke: [.waterGunFast,.psyshock],
            .slowbro: [.confusionFast,.iceBeam],
            .magnemite: [.thunderShockFast,.magnetBomb],
            .magneton: [.chargeBeamFast,.magnetBomb],
            .farfetchd: [.airSlashFast,.leafBlade],
            .doduo: [.peckFast,.drillPeck],
            .dodrio: [.feintAttackFast,.drillPeck],
            .seel: [.iceShardFast,.aquaTail],
            .dewgong: [.ironTailFast,.auroraBeam],
            .grimer: [.mudSlapFast,.sludgeBomb],
            .muk: [.poisonJabFast,.gunkShot],
            .shellder: [.iceShardFast,.waterPulse],
            .cloyster: [.iceShardFast,.avalanche],
            .gastly: [.astonishFast,.sludgeBomb],
            .haunter: [.astonishFast,.sludgeBomb],
            .gengar: [.hexFast,.shadowBall],
            .onix: [.rockThrowFast,.sandTomb],
            .drowzee: [.confusionFast,.psyshock],
            .hypno: [.confusionFast,.futuresight],
            .krabby: [.bubbleFast,.waterPulse],
            .kingler: [.bubbleFast,.waterPulse],
            .voltorb: [.sparkFast,.thunderbolt],
            .electrode: [.voltSwitchFast,.discharge],
            .exeggcute: [.confusionFast,.seedBomb],
            .exeggutor: [.extrasensoryFast,.solarBeam],
            .cubone: [.mudSlapFast,.dig],
            .marowak: [.mudSlapFast,.dig],
            .hitmonlee: [.rockSmashFast,.closeCombat],
            .hitmonchan: [.counterFast,.firePunch],
            .lickitung: [.zenHeadbuttFast,.hyperBeam],
            .koffing: [.infestationFast,.sludgeBomb],
            .weezing: [.infestationFast,.sludgeBomb],
            .rhyhorn: [.mudSlapFast,.bulldoze],
            .rhydon: [.mudSlapFast,.earthquake],
            .chansey: [.zenHeadbuttFast,.hyperBeam],
            .tangela: [.infestationFast,.solarBeam],
            .kangaskhan: [.mudSlapFast,.outrage],
            .horsea: [.bubbleFast,.dragonPulse],
            .seadra: [.waterGunFast,.dragonPulse],
            .goldeen: [.peckFast,.aquaTail],
            .seaking: [.poisonJabFast,.iceBeam],
            .staryu: [.waterGunFast,.bubbleBeam],
            .starmie: [.hiddenPowerFast,.hydroPump],
            .mrMime: [.confusionFast,.shadowBall],
            .scyther: [.airSlashFast,.aerialAce],
            .jynx: [.confusionFast,.avalanche],
            .electabuzz: [.thunderShockFast,.thunderbolt],
            .magmar: [.emberFast,.fireBlast],
            .pinsir: [.rockSmashFast,.xScissor],
            .tauros: [.zenHeadbuttFast,.hornAttack],
            .magikarp: [.splashFast,.struggle],
            .gyarados: [.dragonTailFast,.outrage],
            .lapras: [.waterGunFast,.iceBeam],
            .ditto: [.transformFast,.struggle],
            .eevee: [.quickAttackFast,.dig],
            .vaporeon: [.waterGunFast,.aquaTail],
            .jolteon: [.voltSwitchFast,.discharge],
            .flareon: [.fireSpinFast,.overheat],
            .porygon: [.hiddenPowerFast, .hyperBeam],
            .omanyte: [.waterGunFast,.ancientPower],
            .omastar: [.waterGunFast,.ancientPower],
            .kabuto: [.scratchFast,.ancientPower],
            .kabutops: [.rockSmashFast,.ancientPower],
            .aerodactyl: [.steelWingFast,.ancientPower],
            .snorlax: [.zenHeadbuttFast,.hyperBeam],
            .articuno: [.frostBreathFast,.iceBeam],
            .zapdos: [.chargeBeamFast,.thunderbolt],
            .moltres: [.chargeBeamFast,.thunderbolt],
            .dratini: [.dragonBreathFast,.wrap],
            .dragonair: [.dragonBreathFast,.dragonPulse],
            .dragonite: [.dragonTailFast,.outrage],
            .mewtwo: [.confusionFast,.shadowBall],
            .mew: [.poundFast,.solarBeam],
            .chikorita: [.tackleFast,.grassKnot],
            .bayleef: [.razorLeafFast,.grassKnot],
            .meganium: [.razorLeafFast,.solarBeam],
            .cyndaquil: [.emberFast,.flameCharge],
            .quilava: [.emberFast,.flameCharge],
            .typhlosion: [.emberFast,.overheat],
            .totodile: [.scratchFast,.crunch],
            .croconaw: [.scratchFast,.crunch],
            .feraligatr: [.waterGunFast,.iceBeam],
            .sentret: [.scratchFast,.grassKnot],
            .furret: [.quickAttackFast,.hyperBeam],
            .hoothoot: [.feintAttackFast,.skyAttack],
            .noctowl: [.wingAttackFast,.skyAttack],
            .ledyba: [.tackleFast,.silverWind],
            .ledian: [.struggleBugFast,.bugBuzz],
            .spinarak: [.poisonStingFast,.signalBeam],
            .ariados: [.infestationFast,.crossPoison],
            .crobat: [.airSlashFast,.sludgeBomb],
            .chinchou: [.bubbleFast,.thunderbolt],
            .lanturn: [.chargeBeamFast,.thunderbolt],
            .pichu: [.thunderShockFast,.thunderbolt],
            .cleffa: [.zenHeadbuttFast,.grassKnot],
            .igglybuff: [.feintAttackFast,.shadowBall],
            .togepi: [.hiddenPowerFast,.dazzlingGleam],
            .togetic: [.hiddenPowerFast,.dazzlingGleam],
            .natu: [.peckFast,.psyshock],
            .xatu: [.airSlashFast,.aerialAce],
            .mareep: [.thunderShockFast,.discharge],
            .flaaffy: [.chargeBeamFast,.discharge],
            .ampharos: [.voltSwitchFast,.zapCannon],
            .bellossom: [.razorLeafFast,.leafBlade],
            .marill: [.bubbleFast,.aquaTail],
            .azumarill: [.bubbleFast,.playRough],
            .sudowoodo: [.rockThrowFast,.rockSlide],
            .politoed: [.bubbleFast,.hydroPump],
            .hoppip: [.bulletSeedFast,.grassKnot],
            .skiploom: [.bulletSeedFast,.grassKnot],
            .jumpluff: [.infestationFast,.solarBeam],
            .aipom: [.scratchFast,.swift],
            .sunkern: [.razorLeafFast,.grassKnot],
            .sunflora: [.razorLeafFast,.solarBeam],
            .yanma: [.wingAttackFast,.silverWind],
            .wooper: [.waterGunFast,.dig],
            .quagsire: [.mudShotFast,.earthquake],
            .espeon: [.confusionFast,.futuresight],
            .umbreon: [.snarlFast,.darkPulse],
            .murkrow: [.feintAttackFast,.foulPlay],
            .slowking: [.confusionFast,.fireBlast],
            .misdreavus: [.hexFast,.ominousWind],
            .unown: [.hiddenPowerFast,.struggle],
            .wobbuffet: [.counterFast,.mirrorCoat],
            .girafarig: [.confusionFast,.thunderbolt],
            .pineco: [.tackleFast,.gyroBall],
            .forretress: [.struggleBugFast,.heavySlam],
            .dunsparce: [.astonishFast,.dig],
            .gligar: [.wingAttackFast,.dig],
            .steelix: [.ironTailFast,.heavySlam],
            .snubbull: [.biteFast,.dazzlingGleam],
            .granbull: [.snarlFast,.playRough],
            .qwilfish: [.waterGunFast,.aquaTail],
            .scizor: [.bulletPunchFast,.ironHead],
            .shuckle: [.rockThrowFast,.rockBlast],
            .heracross: [.counterFast,.closeCombat],
            .sneasel: [.iceShardFast,.avalanche],
            .teddiursa: [.scratchFast,.playRough],
            .ursaring: [.counterFast,.hyperBeam],
            .slugma: [.rockThrowFast,.flameBurst],
            .magcargo: [.rockThrowFast,.overheat],
            .swinub: [.powderSnowFast,.icyWind],
            .piloswine: [.powderSnowFast,.avalanche],
            .corsola: [.bubbleFast,.powerGem],
            .remoraid: [.waterGunFast,.waterPulse],
            .octillery: [.waterGunFast,.waterPulse],
            .delibird: [.iceShardFast,.aerialAce],
            .mantine: [.bubbleFast,.aerialAce],
            .skarmory: [.airSlashFast,.skyAttack],
            .houndour: [.feintAttackFast,.crunch],
            .houndoom: [.snarlFast,.crunch],
            .kingdra: [.dragonBreathFast,.outrage],
            .phanpy: [.rockSmashFast,.bulldoze],
            .donphan: [.counterFast,.playRough],
            .porygon2: [.hiddenPowerFast,.hyperBeam],
            .stantler: [.zenHeadbuttFast,.wildCharge],
            .smeargle: [.tackleFast,.struggle],
            .tyrogue: [.rockSmashFast,.rockSlide],
            .hitmontop: [.rockSmashFast,.gyroBall],
            .smoochum: [.powderSnowFast,.psyshock],
            .elekid: [.thunderShockFast,.discharge],
            .magby: [.emberFast,.firePunch],
            .miltank: [.zenHeadbuttFast,.bodySlam],
            .blissey: [.zenHeadbuttFast,.hyperBeam],
            .raikou: [.voltSwitchFast,.wildCharge],
            .entei: [.fireSpinFast,.overheat],
            .suicune: [.extrasensoryFast,.hydroPump],
            .larvitar: [.rockSmashFast,.ancientPower],
            .pupitar: [.rockSmashFast,.dig],
            .tyranitar: [.ironTailFast,.crunch],
            .lugia: [.extrasensoryFast,.futuresight],
            .hoOh: [.extrasensoryFast,.fireBlast],
            .celebi: [.confusionFast,.dazzlingGleam]
    ]
    
    static let pokemonBaseQuickMoveDictionary: [PokemonId: [PokemonMove]] =
        [
            .bulbasaur: [.tackleFast,.vineWhipFast],
            .ivysaur: [.razorLeafFast,.vineWhipFast],
            .venusaur: [.razorLeafFast,.vineWhipFast],
            .charmander: [.scratchFast,.emberFast],
            .charmeleon: [.fireFangFast,.emberFast],
            .charizard: [.airSlashFast,.fireSpinFast],
            .squirtle: [.bubbleFast,.tackleFast],
            .wartortle: [.waterGunFast,.biteFast],
            .blastoise: [.waterGunFast,.biteFast],
            .caterpie: [.tackleFast,.bugBiteFast],
            .metapod: [.tackleFast,.bugBiteFast],
            .butterfree: [.confusionFast,.struggleBugFast],
            .weedle: [.poisonStingFast,.bugBiteFast],
            .kakuna: [.poisonStingFast,.bugBiteFast],
            .beedrill: [.poisonJabFast,.infestationFast],
            .pidgey: [.tackleFast,.quickAttackFast],
            .pidgeotto: [.wingAttackFast,.steelWingFast],
            .pidgeot: [.airSlashFast,.steelWingFast],
            .rattata: [.tackleFast,.quickAttackFast],
            .raticate: [.biteFast,.quickAttackFast],
            .spearow: [.quickAttackFast,.peckFast],
            .fearow: [.steelWingFast,.peckFast],
            .ekans: [.acidFast,.poisonStingFast],
            .arbok: [.biteFast,.acidFast],
            .pikachu: [.quickAttackFast,.thunderShockFast],
            .raichu: [.sparkFast,.voltSwitchFast],
            .sandshrew: [.scratchFast,.mudShotFast],
            .sandslash: [.mudShotFast,.metalClawFast],
            .nidoranFemale: [.biteFast,.poisonStingFast],
            .nidorina: [.biteFast,.poisonStingFast],
            .nidoqueen: [.poisonJabFast,.biteFast],
            .nidoranMale: [.poisonStingFast,.peckFast],
            .nidorino: [.poisonJabFast,.poisonStingFast],
            .nidoking: [.poisonJabFast,.ironTailFast],
            .clefairy: [.zenHeadbuttFast,.poundFast],
            .clefable: [.zenHeadbuttFast,.chargeBeamFast],
            .vulpix: [.emberFast,.quickAttackFast],
            .ninetales: [.fireSpinFast,.feintAttackFast],
            .jigglypuff: [.poundFast,.feintAttackFast],
            .wigglytuff: [.poundFast,.feintAttackFast],
            .zubat: [.biteFast,.quickAttackFast],
            .golbat: [.biteFast,.wingAttackFast],
            .oddish: [.razorLeafFast,.acidFast],
            .gloom: [.razorLeafFast,.acidFast],
            .vileplume: [.razorLeafFast,.acidFast],
            .paras: [.scratchFast,.bugBiteFast],
            .parasect: [.struggleBugFast,.furyCutterFast],
            .venonat: [.confusionFast,.bugBiteFast],
            .venomoth: [.confusionFast,.infestationFast],
            .diglett: [.scratchFast,.mudSlapFast],
            .dugtrio: [.mudSlapFast,.suckerPunchFast],
            .meowth: [.scratchFast,.biteFast],
            .persian: [.scratchFast,.feintAttackFast],
            .psyduck: [.waterGunFast,.zenHeadbuttFast],
            .golduck: [.waterGunFast,.confusionFast],
            .mankey: [.scratchFast,.karateChopFast],
            .primeape: [.counterFast,.lowKickFast],
            .growlithe: [.biteFast,.emberFast],
            .arcanine: [.fireFangFast,.snarlFast],
            .poliwag: [.bubbleFast,.mudShotFast],
            .poliwhirl: [.bubbleFast,.mudShotFast],
            .poliwrath: [.bubbleFast,.rockSmashFast],
            .abra: [.zenHeadbuttFast,.chargeBeamFast],
            .kadabra: [.confusionFast,.psychoCutFast],
            .alakazam: [.confusionFast,.psychoCutFast],
            .machop: [.rockSmashFast,.karateChopFast],
            .machoke: [.karateChopFast,.lowKickFast],
            .machamp: [.counterFast,.bulletPunchFast],
            .bellsprout: [.acidFast,.vineWhipFast],
            .weepinbell: [.acidFast,.bulletSeedFast],
            .victreebel: [.razorLeafFast,.acidFast],
            .tentacool: [.bubbleFast,.poisonStingFast],
            .tentacruel: [.poisonJabFast,.acidFast],
            .geodude: [.rockThrowFast,.tackleFast],
            .graveler: [.rockThrowFast,.mudSlapFast],
            .golem: [.rockThrowFast,.mudSlapFast],
            .ponyta: [.tackleFast,.emberFast],
            .rapidash: [.fireSpinFast,.lowKickFast],
            .slowpoke: [.waterGunFast,.confusionFast],
            .slowbro: [.waterGunFast,.confusionFast],
            .magnemite: [.sparkFast,.thunderShockFast],
            .magneton: [.sparkFast,.chargeBeamFast],
            .farfetchd: [.airSlashFast,.furyCutterFast],
            .doduo: [.quickAttackFast,.peckFast],
            .dodrio: [.steelWingFast,.feintAttackFast],
            .seel: [.iceShardFast,.lickFast],
            .dewgong: [.ironTailFast,.frostBreathFast],
            .grimer: [.poisonJabFast,.mudSlapFast],
            .muk: [.poisonJabFast,.infestationFast],
            .shellder: [.tackleFast,.iceShardFast],
            .cloyster: [.frostBreathFast,.iceShardFast],
            .gastly: [.astonishFast,.lickFast],
            .haunter: [.shadowClawFast,.astonishFast],
            .gengar: [.hexFast,.suckerPunchFast],
            .onix: [.rockThrowFast,.tackleFast],
            .drowzee: [.confusionFast,.poundFast],
            .hypno: [.confusionFast,.zenHeadbuttFast],
            .krabby: [.bubbleFast,.mudShotFast],
            .kingler: [.bubbleFast,.metalClawFast],
            .voltorb: [.tackleFast,.sparkFast],
            .electrode: [.sparkFast,.voltSwitchFast],
            .exeggcute: [.confusionFast,.bulletSeedFast],
            .exeggutor: [.extrasensoryFast,.bulletSeedFast],
            .cubone: [.mudSlapFast,.rockSmashFast],
            .marowak: [.mudSlapFast,.rockSmashFast],
            .hitmonlee: [.rockSmashFast,.lowKickFast],
            .hitmonchan: [.counterFast,.bulletPunchFast],
            .lickitung: [.zenHeadbuttFast,.lickFast],
            .koffing: [.tackleFast,.infestationFast],
            .weezing: [.tackleFast,.infestationFast],
            .rhyhorn: [.mudSlapFast,.rockSmashFast],
            .rhydon: [.mudSlapFast,.rockSmashFast],
            .chansey: [.poundFast,.zenHeadbuttFast],
            .tangela: [.vineWhipFast,.infestationFast],
            .kangaskhan: [.mudSlapFast,.lowKickFast],
            .horsea: [.waterGunFast,.bubbleFast],
            .seadra: [.waterGunFast,.dragonBreathFast],
            .goldeen: [.mudShotFast,.peckFast],
            .seaking: [.poisonJabFast,.peckFast],
            .staryu: [.waterGunFast,.tackleFast],
            .starmie: [.waterGunFast,.hiddenPowerFast],
            .mrMime: [.confusionFast,.zenHeadbuttFast],
            .scyther: [.airSlashFast,.furyCutterFast],
            .jynx: [.confusionFast,.frostBreathFast],
            .electabuzz: [.thunderShockFast,.lowKickFast],
            .magmar: [.emberFast,.karateChopFast],
            .pinsir: [.rockSmashFast,.bugBiteFast],
            .tauros: [.tackleFast,.zenHeadbuttFast],
            .magikarp: [.splashFast],
            .gyarados: [.biteFast,.dragonTailFast],
            .lapras: [.waterGunFast,.frostBreathFast],
            .ditto: [.transformFast],
            .eevee: [.tackleFast,.quickAttackFast],
            .vaporeon: [.waterGunFast],
            .jolteon: [.thunderShockFast,.voltSwitchFast],
            .flareon: [.fireSpinFast,.emberFast],
            .porygon: [.hiddenPowerFast,.chargeBeamFast],
            .omanyte: [.waterGunFast,.mudShotFast],
            .omastar: [.waterGunFast,.mudShotFast],
            .kabuto: [.scratchFast,.mudShotFast],
            .kabutops: [.rockSmashFast,.mudShotFast],
            .aerodactyl: [.biteFast,.steelWingFast],
            .snorlax: [.zenHeadbuttFast,.lickFast],
            .articuno: [.frostBreathFast],
            .zapdos: [.chargeBeamFast],
            .moltres: [.fireSpinFast],
            .dratini: [.dragonBreathFast,.ironTailFast],
            .dragonair: [.dragonBreathFast,.ironTailFast],
            .dragonite: [.dragonTailFast,.steelWingFast],
            .mewtwo: [.confusionFast,.psychoCutFast],
            .mew: [.poundFast],
            .chikorita: [.tackleFast,.vineWhipFast],
            .bayleef: [.razorLeafFast,.tackleFast],
            .meganium: [.razorLeafFast,.vineWhipFast],
            .cyndaquil: [.tackleFast,.emberFast],
            .quilava: [.tackleFast,.emberFast],
            .typhlosion: [.shadowClawFast,.emberFast],
            .totodile: [.waterGunFast,.scratchFast],
            .croconaw: [.waterGunFast,.scratchFast],
            .feraligatr: [.waterGunFast,.biteFast],
            .sentret: [.scratchFast,.quickAttackFast],
            .furret: [.quickAttackFast,.suckerPunchFast],
            .hoothoot: [.feintAttackFast,.peckFast],
            .noctowl: [.wingAttackFast,.extrasensoryFast],
            .ledyba: [.tackleFast,.bugBiteFast],
            .ledian: [.bugBiteFast,.struggleBugFast],
            .spinarak: [.poisonStingFast,.bugBiteFast],
            .ariados: [.infestationFast,.poisonStingFast],
            .crobat: [.airSlashFast,.biteFast],
            .chinchou: [.bubbleFast,.sparkFast],
            .lanturn: [.waterGunFast,.chargeBeamFast],
            .pichu: [.thunderShockFast],
            .cleffa: [.zenHeadbuttFast,.poundFast],
            .igglybuff: [.poundFast,.feintAttackFast],
            .togepi: [.peckFast,.hiddenPowerFast],
            .togetic: [.extrasensoryFast,.hiddenPowerFast],
            .natu: [.peckFast,.quickAttackFast],
            .xatu: [.airSlashFast,.feintAttackFast],
            .mareep: [.tackleFast,.thunderShockFast],
            .flaaffy: [.tackleFast,.chargeBeamFast],
            .ampharos: [.voltSwitchFast,.chargeBeamFast],
            .bellossom: [.razorLeafFast,.acidFast],
            .marill: [.bubbleFast,.tackleFast],
            .azumarill: [.bubbleFast,.rockSmashFast],
            .sudowoodo: [.counterFast,.rockThrowFast],
            .politoed: [.bubbleFast,.mudShotFast],
            .hoppip: [.tackleFast,.bulletSeedFast],
            .skiploom: [.tackleFast,.bulletSeedFast],
            .jumpluff: [.bulletSeedFast,.infestationFast],
            .aipom: [.scratchFast,.astonishFast],
            .sunkern: [.razorLeafFast,.cutFast],
            .sunflora: [.razorLeafFast,.bulletSeedFast],
            .yanma: [.wingAttackFast,.quickAttackFast],
            .wooper: [.waterGunFast,.mudShotFast],
            .quagsire: [.waterGunFast,.mudShotFast],
            .espeon: [.confusionFast,.zenHeadbuttFast],
            .umbreon: [.feintAttackFast,.snarlFast],
            .murkrow: [.feintAttackFast,.peckFast],
            .slowking: [.waterGunFast,.confusionFast],
            .misdreavus: [.hexFast,.astonishFast],
            .unown: [.hiddenPowerFast],
            .wobbuffet: [.counterFast,.splashFast],
            .girafarig: [.tackleFast,.confusionFast],
            .pineco: [.tackleFast,.bugBiteFast],
            .forretress: [.bugBiteFast,.struggleBugFast],
            .dunsparce: [.biteFast,.astonishFast],
            .gligar: [.wingAttackFast,.furyCutterFast],
            .steelix: [.ironTailFast,.dragonTailFast],
            .snubbull: [.tackleFast,.biteFast],
            .granbull: [.biteFast,.snarlFast],
            .qwilfish: [.waterGunFast,.poisonStingFast],
            .scizor: [.bulletPunchFast,.furyCutterFast],
            .shuckle: [.rockThrowFast,.struggleBugFast],
            .heracross: [.counterFast,.struggleBugFast],
            .sneasel: [.feintAttackFast,.iceShardFast],
            .teddiursa: [.scratchFast,.lickFast],
            .ursaring: [.counterFast,.metalClawFast],
            .slugma: [.rockThrowFast,.emberFast],
            .magcargo: [.rockThrowFast,.emberFast],
            .swinub: [.tackleFast,.powderSnowFast],
            .piloswine: [.iceShardFast,.powderSnowFast],
            .corsola: [.bubbleFast,.tackleFast],
            .remoraid: [.waterGunFast,.mudShotFast],
            .octillery: [.waterGunFast,.mudShotFast],
            .delibird: [.iceShardFast,.quickAttackFast],
            .mantine: [.bubbleFast,.wingAttackFast],
            .skarmory: [.airSlashFast,.steelWingFast],
            .houndour: [.feintAttackFast,.emberFast],
            .houndoom: [.fireFangFast,.snarlFast],
            .kingdra: [.dragonBreathFast,.waterGunFast],
            .phanpy: [.tackleFast,.rockSmashFast],
            .donphan: [.counterFast,.tackleFast],
            .porygon2: [.hiddenPowerFast,.chargeBeamFast],
            .stantler: [.tackleFast,.zenHeadbuttFast],
            .smeargle: [.tackleFast],
            .tyrogue: [.rockSmashFast,.tackleFast],
            .hitmontop: [.counterFast,.rockSmashFast],
            .smoochum: [.poundFast,.powderSnowFast],
            .elekid: [.thunderShockFast,.lowKickFast],
            .magby: [.emberFast,.karateChopFast],
            .miltank: [.tackleFast,.zenHeadbuttFast],
            .blissey: [.poundFast,.zenHeadbuttFast],
            .raikou: [.thunderShockFast,.voltSwitchFast],
            .entei: [.fireSpinFast,.fireFangFast],
            .suicune: [.extrasensoryFast,.snarlFast],
            .larvitar: [.biteFast,.rockSmashFast],
            .pupitar: [.biteFast,.rockSmashFast],
            .tyranitar: [.biteFast,.ironTailFast],
            .lugia: [.extrasensoryFast,.dragonTailFast],
            .hoOh: [.steelWingFast,.extrasensoryFast],
            .celebi: [.confusionFast,.chargeBeamFast]
    ]
    
    static let pokemonBaseMainMoveDictionary: [PokemonId: [PokemonMove]] =
        [
            .bulbasaur: [.sludgeBomb,.powerWhip,.seedBomb],
            .ivysaur: [.solarBeam,.sludgeBomb,.powerWhip],
            .venusaur: [.petalBlizzard,.solarBeam,.sludgeBomb],
            .charmander: [.flamethrower,.flameBurst,.flameCharge],
            .charmeleon: [.flamethrower,.flameBurst,.firePunch],
            .charizard: [.overheat,.fireBlast,.dragonClaw],
            .squirtle: [.aquaTail,.waterPulse,.aquaJet],
            .wartortle: [.hydroPump,.iceBeam,.aquaJet],
            .blastoise: [.hydroPump,.flashCannon,.iceBeam],
            .caterpie: [.struggle],
            .metapod: [.struggle],
            .butterfree: [.psychic,.signalBeam,.bugBuzz],
            .weedle: [.struggle],
            .kakuna: [.struggle],
            .beedrill: [.sludgeBomb,.xScissor,.aerialAce],
            .pidgey: [.aerialAce,.airCutter,.twister],
            .pidgeotto: [.aerialAce,.airCutter,.twister],
            .pidgeot: [.braveBird,.hurricane,.aerialAce],
            .rattata: [.hyperFang,.bodySlam,.dig],
            .raticate: [.hyperBeam,.hyperFang,.dig],
            .spearow: [.skyAttack,.drillPeck,.aerialAce],
            .fearow: [.skyAttack,.aerialAce,.drillRun],
            .ekans: [.sludgeBomb,.poisonFang,.wrap],
            .arbok: [.gunkShot,.sludgeWave,.darkPulse],
            .pikachu: [.wildCharge,.thunderbolt,.discharge],
            .raichu: [.wildCharge,.thunderPunch,.brickBreak],
            .sandshrew: [.rockSlide,.dig,.sandTomb],
            .sandslash: [.earthquake,.bulldoze,.rockTomb],
            .nidoranFemale: [.sludgeBomb,.bodySlam,.poisonFang],
            .nidorina: [.sludgeBomb,.poisonFang,.dig],
            .nidoqueen: [.stoneEdge,.sludgeWave,.earthquake],
            .nidoranMale: [.sludgeBomb,.bodySlam,.hornAttack],
            .nidorino: [.sludgeBomb,.hornAttack,.dig],
            .nidoking: [.sludgeWave,.earthquake,.megahorn],
            .clefairy: [.moonblast,.bodySlam,.disarmingVoice],
            .clefable: [.moonblast,.dazzlingGleam,.psychic],
            .vulpix: [.flamethrower,.bodySlam,.flameCharge],
            .ninetales: [.overheat,.heatWave,.solarBeam],
            .jigglypuff: [.dazzlingGleam,.gyroBall,.disarmingVoice],
            .wigglytuff: [.hyperBeam,.playRough,.dazzlingGleam],
            .zubat: [.airCutter,.poisonFang,.swift],
            .golbat: [.shadowBall,.airCutter,.poisonFang],
            .oddish: [.sludgeBomb,.moonblast,.seedBomb],
            .gloom: [.petalBlizzard,.sludgeBomb,.moonblast],
            .vileplume: [.petalBlizzard,.solarBeam,.moonblast],
            .paras: [.xScissor,.seedBomb,.crossPoison],
            .parasect: [.solarBeam,.xScissor,.crossPoison],
            .venonat: [.signalBeam,.poisonFang,.psybeam],
            .venomoth: [.psychic,.bugBuzz,.silverWind],
            .diglett: [.mudBomb,.dig,.rockTomb],
            .dugtrio: [.stoneEdge,.earthquake,.mudBomb],
            .meowth: [.foulPlay,.darkPulse,.nightSlash],
            .persian: [.foulPlay,.playRough,.powerGem],
            .psyduck: [.crossChop,.aquaTail,.psybeam],
            .golduck: [.hydroPump,.psychic,.iceBeam],
            .mankey: [.crossChop,.brickBreak,.lowSweep],
            .primeape: [.closeCombat,.lowSweep,.nightSlash],
            .growlithe: [.flamethrower,.flameWheel,.bodySlam],
            .arcanine: [.fireBlast,.wildCharge,.crunch],
            .poliwag: [.bubbleBeam,.bodySlam,.mudBomb],
            .poliwhirl: [.bubbleBeam,.waterPulse,.mudBomb],
            .poliwrath: [.hydroPump,.dynamicPunch,.icePunch],
            .abra: [.shadowBall,.psyshock,.signalBeam],
            .kadabra: [.shadowBall,.dazzlingGleam,.psybeam],
            .alakazam: [.futuresight,.focusBlast,.shadowBall],
            .machop: [.crossChop,.brickBreak,.lowSweep],
            .machoke: [.dynamicPunch,.submission,.brickBreak],
            .machamp: [.closeCombat,.dynamicPunch,.heavySlam],
            .bellsprout: [.sludgeBomb,.powerWhip,.wrap],
            .weepinbell: [.sludgeBomb,.powerWhip,.seedBomb],
            .victreebel: [.solarBeam,.sludgeBomb,.leafBlade],
            .tentacool: [.bubbleBeam,.waterPulse,.wrap],
            .tentacruel: [.hydroPump,.sludgeWave,.blizzard],
            .geodude: [.rockSlide,.rockTomb,.dig],
            .graveler: [.stoneEdge,.rockBlast,.dig],
            .golem: [.stoneEdge,.earthquake,.rockBlast],
            .ponyta: [.stomp,.flameWheel,.flameCharge],
            .rapidash: [.fireBlast,.heatWave,.drillRun],
            .slowpoke: [.psychic,.psyshock,.waterPulse],
            .slowbro: [.psychic,.waterPulse,.iceBeam],
            .magnemite: [.thunderbolt,.discharge,.magnetBomb],
            .magneton: [.zapCannon,.flashCannon,.magnetBomb],
            .farfetchd: [.leafBlade,.aerialAce,.airCutter],
            .doduo: [.braveBird,.drillPeck,.aerialAce],
            .dodrio: [.braveBird,.drillPeck,.aerialAce],
            .seel: [.aquaTail,.auroraBeam,.icyWind],
            .dewgong: [.blizzard,.auroraBeam,.waterPulse],
            .grimer: [.sludgeBomb,.sludge,.mudBomb],
            .muk: [.gunkShot,.sludgeWave,.darkPulse],
            .shellder: [.bubbleBeam,.waterPulse,.icyWind],
            .cloyster: [.hydroPump,.avalanche,.auroraBeam],
            .gastly: [.sludgeBomb,.nightShade,.darkPulse],
            .haunter: [.sludgeBomb,.shadowPunch,.darkPulse],
            .gengar: [.sludgeBomb,.shadowBall,.focusBlast],
            .onix: [.stoneEdge,.heavySlam,.sandTomb],
            .drowzee: [.psychic,.psyshock,.psybeam],
            .hypno: [.futuresight,.psychic,.focusBlast],
            .krabby: [.bubbleBeam,.waterPulse,.viceGrip],
            .kingler: [.xScissor,.waterPulse,.viceGrip],
            .voltorb: [.thunderbolt,.discharge,.gyroBall],
            .electrode: [.thunderbolt,.hyperBeam,.discharge],
            .exeggcute: [.psychic,.seedBomb,.ancientPower],
            .exeggutor: [.solarBeam,.psychic,.seedBomb],
            .cubone: [.boneClub,.bulldoze,.dig],
            .marowak: [.earthquake,.boneClub,.dig],
            .hitmonlee: [.closeCombat,.stoneEdge,.lowSweep],
            .hitmonchan: [.closeCombat,.icePunch,.thunderPunch,.firePunch],
            .lickitung: [.hyperBeam,.stomp,.powerWhip],
            .koffing: [.sludgeBomb,.sludge,.darkPulse],
            .weezing: [.sludgeBomb,.shadowBall,.darkPulse],
            .rhyhorn: [.stomp,.bulldoze,.hornAttack],
            .rhydon: [.stoneEdge,.earthquake,.megahorn],
            .chansey: [.hyperBeam,.psychic,.dazzlingGleam],
            .tangela: [.solarBeam,.grassKnot,.sludgeBomb],
            .kangaskhan: [.earthquake,.outrage,.crunch],
            .horsea: [.flashCannon,.bubbleBeam,.dragonPulse],
            .seadra: [.hydroPump,.dragonPulse,.auroraBeam],
            .goldeen: [.aquaTail,.waterPulse,.hornAttack],
            .seaking: [.megahorn,.waterPulse,.iceBeam],
            .staryu: [.bubbleBeam,.powerGem,.swift],
            .starmie: [.hydroPump,.psychic,.powerGem],
            .mrMime: [.psychic,.shadowBall,.psybeam],
            .scyther: [.xScissor,.aerialAce,.nightSlash],
            .jynx: [.avalanche,.psyshock,.drainingKiss],
            .electabuzz: [.thunder,.thunderbolt,.thunderPunch],
            .magmar: [.fireBlast,.flamethrower,.firePunch],
            .pinsir: [.closeCombat,.xScissor,.viceGrip],
            .tauros: [.earthquake,.ironHead,.hornAttack],
            .magikarp: [.struggle],
            .gyarados: [.hydroPump,.outrage,.crunch],
            .lapras: [.blizzard,.hydroPump,.iceBeam],
            .ditto: [.struggle],
            .eevee: [.swift,.dig],
            .vaporeon: [.hydroPump,.aquaTail,.waterPulse],
            .jolteon: [.thunder,.thunderbolt,.discharge],
            .flareon: [.overheat,.fireBlast,.flamethrower],
            .porygon: [.hyperBeam,.zapCannon,.solarBeam],
            .omanyte: [.rockBlast,.bubbleBeam,.ancientPower],
            .omastar: [.hydroPump,.rockBlast,.ancientPower],
            .kabuto: [.rockTomb,.ancientPower,.aquaJet],
            .kabutops: [.stoneEdge,.waterPulse,.ancientPower],
            .aerodactyl: [.hyperBeam,.ironHead,.ancientPower],
            .snorlax: [.hyperBeam,.earthquake,.heavySlam],
            .articuno: [.blizzard,.iceBeam,.icyWind],
            .zapdos: [.thunder,.zapCannon,.thunderbolt],
            .moltres: [.overheat,.fireBlast,.heatWave],
            .dratini: [.aquaTail,.wrap,.twister],
            .dragonair: [.dragonPulse,.aquaTail,.wrap],
            .dragonite: [.hurricane,.hyperBeam,.outrage],
            .mewtwo: [.psychic,.focusBlast,.hyperBeam,.shadowBall],
            .mew: [.psychic,.blizzard,.thunder,.focusBlast,.hyperBeam,.solarBeam,.earthquake,.fireBlast],
            .chikorita: [.grassKnot,.energyBall,.bodySlam],
            .bayleef: [.grassKnot,.energyBall,.ancientPower],
            .meganium: [.petalBlizzard,.solarBeam,.earthquake],
            .cyndaquil: [.flamethrower,.flameCharge,.swift],
            .quilava: [.flamethrower,.flameCharge,.dig],
            .typhlosion: [.overheat,.fireBlast,.solarBeam],
            .totodile: [.waterPulse,.crunch,.aquaJet],
            .croconaw: [.waterPulse,.icePunch,.crunch],
            .feraligatr: [.hydroPump,.iceBeam,.crunch],
            .sentret: [.grassKnot,.brickBreak,.dig],
            .furret: [.hyperBeam,.brickBreak,.dig],
            .hoothoot: [.skyAttack,.aerialAce,.nightShade],
            .noctowl: [.skyAttack,.psychic,.nightShade],
            .ledyba: [.aerialAce,.silverWind,.swift],
            .ledian: [.bugBuzz,.aerialAce,.silverWind],
            .spinarak: [.crossPoison,.signalBeam,.nightSlash],
            .ariados: [.megahorn,.crossPoison,.shadowSneak],
            .crobat: [.sludgeBomb,.shadowBall,.airCutter],
            .chinchou: [.thunderbolt,.bubbleBeam,.waterPulse],
            .lanturn: [.thunder,.hydroPump,.thunderbolt],
            .pichu: [.thunderbolt,.thunderPunch,.disarmingVoice],
            .cleffa: [.grassKnot,.signalBeam,.psyshock],
            .igglybuff: [.psychic,.wildCharge,.shadowBall],
            .togepi: [.dazzlingGleam,.psyshock,.ancientPower],
            .togetic: [.dazzlingGleam,.aerialAce,.ancientPower],
            .natu: [.drillPeck,.psyshock,.nightShade],
            .xatu: [.futuresight,.aerialAce,.ominousWind],
            .mareep: [.thunderbolt,.discharge,.bodySlam],
            .flaaffy: [.thunderbolt,.discharge,.powerGem],
            .ampharos: [.thunder,.zapCannon,.focusBlast],
            .bellossom: [.petalBlizzard,.leafBlade,.dazzlingGleam],
            .marill: [.aquaTail,.bubbleBeam,.bodySlam],
            .azumarill: [.hydroPump,.playRough,.iceBeam],
            .sudowoodo: [.stoneEdge,.rockSlide,.earthquake],
            .politoed: [.hydroPump,.blizzard,.earthquake],
            .hoppip: [.grassKnot,.seedBomb,.dazzlingGleam],
            .skiploom: [.grassKnot,.energyBall,.dazzlingGleam],
            .jumpluff: [.solarBeam,.energyBall,.dazzlingGleam],
            .aipom: [.swift,.aerialAce,.lowSweep],
            .sunkern: [.grassKnot,.seedBomb,.energyBall],
            .sunflora: [.petalBlizzard,.solarBeam,.sludgeBomb],
            .yanma: [.aerialAce,.silverWind,.ancientPower],
            .wooper: [.mudBomb,.dig,.bodySlam],
            .quagsire: [.stoneEdge,.earthquake,.sludgeBomb],
            .espeon: [.futuresight,.psychic,.psybeam],
            .umbreon: [.foulPlay,.darkPulse],
            .murkrow: [.foulPlay,.darkPulse,.drillPeck],
            .slowking: [.psychic,.blizzard,.fireBlast],
            .misdreavus: [.ominousWind,.darkPulse,.shadowSneak],
            .unown: [.struggle],
            .wobbuffet: [.mirrorCoat],
            .girafarig: [.psychic,.thunderbolt,.mirrorCoat],
            .pineco: [.gyroBall,.rockTomb,.sandTomb],
            .forretress: [.heavySlam,.earthquake,.rockTomb],
            .dunsparce: [.rockSlide,.drillRun,.dig],
            .gligar: [.aerialAce,.dig,.nightSlash],
            .steelix: [.earthquake,.heavySlam,.crunch],
            .snubbull: [.dazzlingGleam,.brickBreak,.crunch],
            .granbull: [.closeCombat,.playRough,.crunch],
            .qwilfish: [.sludgeWave,.aquaTail,.iceBeam],
            .scizor: [.ironHead,.xScissor,.nightSlash],
            .shuckle: [.stoneEdge,.rockBlast,.gyroBall],
            .heracross: [.closeCombat,.megahorn,.earthquake],
            .sneasel: [.foulPlay,.avalanche,.icePunch],
            .teddiursa: [.crossChop,.playRough,.crunch],
            .ursaring: [.hyperBeam,.closeCombat,.playRough],
            .slugma: [.flameBurst,.rockSlide,.flameCharge],
            .magcargo: [.stoneEdge,.overheat,.heatWave],
            .swinub: [.rockSlide,.bodySlam,.icyWind],
            .piloswine: [.stoneEdge,.avalanche,.bulldoze],
            .corsola: [.powerGem,.rockBlast,.bubbleBeam],
            .remoraid: [.waterPulse,.rockBlast,.auroraBeam],
            .octillery: [.gunkShot,.waterPulse,.auroraBeam],
            .delibird: [.icePunch,.aerialAce,.icyWind],
            .mantine: [.aerialAce,.waterPulse,.iceBeam],
            .skarmory: [.braveBird,.flashCannon,.skyAttack],
            .houndour: [.flamethrower,.darkPulse,.crunch],
            .houndoom: [.foulPlay,.fireBlast,.crunch],
            .kingdra: [.hydroPump,.blizzard,.outrage],
            .phanpy: [.rockSlide,.bulldoze,.bodySlam],
            .donphan: [.earthquake,.heavySlam,.playRough],
            .porygon2: [.hyperBeam,.zapCannon,.solarBeam],
            .stantler: [.megahorn,.stomp,.wildCharge],
            .smeargle: [.struggle],
            .tyrogue: [.brickBreak,.rockSlide,.lowSweep],
            .hitmontop: [.closeCombat,.stoneEdge,.gyroBall],
            .smoochum: [.iceBeam,.icePunch,.psyshock],
            .elekid: [.discharge,.thunderPunch,.brickBreak],
            .magby: [.flameBurst,.firePunch,.brickBreak],
            .miltank: [.stomp,.bodySlam,.gyroBall],
            .blissey: [.hyperBeam,.psychic,.dazzlingGleam],
            .raikou: [.thunder,.wildCharge,.thunderbolt],
            .entei: [.overheat,.fireBlast,.flamethrower],
            .suicune: [.hydroPump,.bubbleBeam,.waterPulse],
            .larvitar: [.stomp,.ancientPower,.crunch],
            .pupitar: [.dig,.ancientPower,.crunch],
            .tyranitar: [.stoneEdge,.fireBlast,.crunch],
            .lugia: [.futuresight,.skyAttack,.hydroPump],
            .hoOh: [.braveBird,.fireBlast,.solarBeam],
            .celebi: [.psychic,.hyperBeam,.dazzlingGleam]
    ]
    
}
